name: release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - id: determine-tag-and-build-date
        name: Determine Docker tag
        run: |
          echo build_tag=$(date +%Y-%W) >> $GITHUB_ENV
          echo build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ") >> $GITHUB_ENV

      - name: build Docker file
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64, linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.build_tag }}
            ghcr.io/${{ github.repository }}:latest
